name: real-tests

on: push

jobs:
  real-tests:
    runs-on: macos-latest
    steps:

      - name: checkout git repository
        uses: actions/checkout@v2

      - name: run "make test"
        run: bash -c "make test -C real-tests"
