name: real-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: check status of working directory
        run: |
          pwd
          ls -la

      - name: checkout git repository
        uses: actions/checkout@v2

      - name: run real-tests
        run: bash -c "make test -C real-tests"
