name: tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest
    steps:

      - name: checkout git repository
        uses: actions/checkout@v2

      - name: run "make test"
        run: |
          bash -c "make fclean -C tests"
          bash -c "make test -C tests"
          bash -c "make fclean -C tests"

      - name: run "make test_bonus"
        run: |
          bash -c "make fclean -C tests"
          bash -c "make test_bonus -C tests"
          bash -c "make fclean -C tests"
